services:
  postgres:
    container_name: catalogue-database
    image: postgres:latest
    restart: always
    environment:
      - 'POSTGRES_DB=catalogue'
      - 'POSTGRES_USER=catalogue'
      - 'POSTGRES_PASSWORD=catalogue'
    ports:
      - '5432:5432'

  redis:
    container_name: catalogue-redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
