spring:
  application:
    name: manager-app
  datasource:
    url: jdbc:postgresql://localhost:5432/manager-database
    username: manager
    password: manager
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

newrav1k:
  services:
    catalogue:
      url: http://localhost:8081
      username: catalogue
      password: catalogue