name: TaskControl
services:
  manager-database:
    container_name: manager-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: manager-database
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: manager
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U manager -d manager-database" ]
      interval: 5s
      timeout: 5s
      retries: 5

  catalogue-database:
    container_name: catalogue-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: catalogue-database
      POSTGRES_USER: catalogue
      POSTGRES_PASSWORD: catalogue
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U catalogue -d catalogue-database" ]
      interval: 5s
      timeout: 5s
      retries: 5

  catalogue-redis:
    container_name: catalogue-redis
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  manager-app:
    container_name: manager-service
    build: ../manager-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://manager-database:5432/manager-database
      SPRING_DATASOURCE_USERNAME: manager
      SPRING_DATASOURCE_PASSWORD: manager
    depends_on:
      manager-database:
        condition: service_healthy
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  catalogue-service:
    container_name: catalogue-service
    build: ../catalogue-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://catalogue-database:5432/catalogue-database
      SPRING_DATASOURCE_USERNAME: catalogue
      SPRING_DATASOURCE_PASSWORD: catalogue
    depends_on:
      catalogue-database:
        condition: service_healthy
      catalogue-redis:
        condition: service_healthy
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
