spring:
  application:
    name: catalogue-service
  security:
    user:
      name: catalogue
      password: "{noop}catalogue"
      roles:
        - SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/catalogue-database
    username: catalogue
    password: catalogue
    driver-class-name: org.postgresql.Driver

server:
  port: 8081